version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run:
          name: Initializing deployment.
          command: echo Deploying....
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'