version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Initializing deployment.
          command: echo Deploying....
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'